### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by lczyk** [elexon-data/iris-clients#19]
I'm comparing the data streams between [bmreports api](https://www.bmreports.com) and [iris](https://bmrs.elexon.co.uk/iris) and I found that there are some messages missing from the iris data stream. As an example here is the plot of Physical Notification from T_LLWSD-1 on 28/02/24 (aka today):

<img width="621" alt="Screenshot 2024-02-28 at 15 34 57" src="https://github.com/elexon-data/iris-clients/assets/24707398/fce27837-bb70-4be0-83cb-0ff8d63cb623">

You can see that there is a discrepancy on SP 24 (11:30-12:00 BST). When consulting the bmreports' ["Search by BM Unit"](https://www.bmreports.com/bmrs/?q=balancing/searchbyBMUnit) website I find that that data is indeed correct. When, in turn I consult the elexon's ["Balancing Mechanism data by BMU"](https://bmrs.elexon.co.uk/balancing-mechanism-bmu-view?bmuId=T_LLWSD-1&activeTab=Physical&startDate=2024-02-28T00%3A00%3A00.000Z&endDate=2024-02-28T14%3A30%3A00.000Z) I find that the relevant SP is missing:

<img width="725" alt="Screenshot 2024-02-28 at 15 34 01" src="https://github.com/elexon-data/iris-clients/assets/24707398/b7f31074-afbd-4fcb-b3db-cf52517922d3">

---

This is of course highly troubling since BMRS is [scheduled to be switched off Mid May 2024](https://www.elexon.co.uk/data/kinnect-insights-solution/) (NOTE: <- elexon.co.uk does not work in Safari)

**Comment by lczyk** [comment]
At some point between 14:30 and 16:00 (aka now) the data on [elexon's website(https://bmrs.elexon.co.uk/balancing-mechanism-bmu-view?bmuId=T_LLWSD-1&activeTab=Physical&startDate=2024-02-28T00%3A00%3A00.000Z&endDate=2024-02-28T14%3A30%3A00.000Z) got updated:

<img width="730" alt="Screenshot 2024-02-28 at 15 56 42" src="https://github.com/elexon-data/iris-clients/assets/24707398/52edbf8d-0495-4489-ab0e-5759d766a0ce">

This is still a serious issue since no realtime data was available through iris for *at least 2.5* hours, while it was clearly available through the old data service.

**Comment by beccar97** [comment]
Hi Marcin, 

Thanks for getting in touch 🙂 

There was a planned data outage across both the BM Reports site and the Insights solution today from 10am until 1pm, which was extended until 2pm. This was due to some work behind the scenes relating to the upstream data connections that feed both systems. Between 2pm and 3pm both systems were recovering from this outage, and importing data from that period. You seem to have been incredibly lucky (or unlucky) in when you looked for this, as the file containing the PN data for SP 24 was ingested into the Insights solution, and sent out via IRIS, at 14:43 today, and BM Reports would most likely only have received the same file shortly before this. 

The data outage impacted the majority, but not all datasets for the Insights solution, and IRIS continued to make data available throughout the outage period. The IRIS archive can be used to confirm all the data sent out via IRIS, if you ever wish to check on the time that data was made available through this data stream.

**Comment by lczyk** [comment]
@beccar97 hi :)) thanks for confirming and a very quick response! much appreciated!

just a quick question: i have not seen any information about the outage a priori (in fact, i still don't) on [system events](https://bmrs.elexon.co.uk/events). is that a good place to get information about the outages in the future? ideally i'd love an api endpoint to integrate information about the outages into our system. maybe the [SYSWARN messages](https://bmrs.elexon.co.uk/api-documentation/endpoint/system/warnings)?
